/*
 * Pure env-detection + allowlist helpers (Phase 6G Part 2).
 *
 * Lives separately from ssoConfig.ts so callers + tests can reach
 * the helpers without importing NextAuth (which pulls in next/server
 * and trips up vitest's Node environment).
 */

/**
 * Returns true when every variable needed to actually round-trip a
 * Microsoft sign-in is present. /login uses this for the button's
 * enabled/disabled state.
 *
 * Phase 6G Part 2 update (Anish 2026-05-21 follow-up): Mafatlal IT
 * registered the app as a public client with PKCE, so no client
 * secret is required. Configured envs:
 *   - AUTH_MICROSOFT_ENTRA_ID_ID       (Client ID)
 *   - AUTH_MICROSOFT_ENTRA_ID_TENANT_ID (Tenant ID)
 *   - AUTH_SECRET                      (self-generated by us)
 */
export function isMicrosoftEntraIdConfigured(): boolean {
  return (
    !!process.env.AUTH_MICROSOFT_ENTRA_ID_ID &&
    !!process.env.AUTH_MICROSOFT_ENTRA_ID_TENANT_ID &&
    !!process.env.AUTH_SECRET
  )
}

/** Parse the optional domain allowlist from env. Empty = no allowlist. */
export function parseAllowedDomains(): string[] {
  const raw = process.env.AUTH_MICROSOFT_ENTRA_ID_ALLOWED_DOMAINS ?? ''
  return raw
    .split(',')
    .map((s) => s.trim().toLowerCase())
    .filter((s) => s.length > 0)
}

/** True when the email's domain is allowed (or allowlist is empty). */
export function isEmailDomainAllowed(email: string, allowed?: string[]): boolean {
  const list = allowed ?? parseAllowedDomains()
  if (list.length === 0) return true
  const domain = (email.split('@')[1] ?? '').toLowerCase()
  return list.includes(domain)
}

/**
 * Phase 6G.3 (2026-05-24): build the provider-config object passed to
 * NextAuth's MicrosoftEntraID(). Two shapes depending on whether the
 * Azure app registration is confidential (expects a client secret on
 * /token) or public (PKCE-only).
 *
 *   - If AUTH_MICROSOFT_ENTRA_ID_SECRET is set: confidential client.
 *     We send clientSecret on the token-exchange leg.
 *   - Otherwise: public client + PKCE. We set token_endpoint_auth_method
 *     'none' so postgres.js's underlying openid-client lib does not send
 *     a Basic-auth header that Microsoft would reject for a public app.
 *
 * The first Anish click-test (2026-05-24) failed with invalid_client
 * from Microsoft's /token endpoint while running the public-client
 * config. That signal told us the Azure registration is "Web" platform
 * type (which is always confidential in Entra) rather than "SPA" /
 * "Mobile and desktop applications" (which are public). Either: IT
 * gives us a secret and we set AUTH_MICROSOFT_ENTRA_ID_SECRET, OR IT
 * flips the registration to SPA and we keep the public path. This
 * helper supports both.
 */
export interface EntraProviderConfig {
  clientId: string
  clientSecret?: string
  issuer: string
  client?: { token_endpoint_auth_method: 'none' }
}

export function buildEntraProviderConfig(env: NodeJS.ProcessEnv = process.env): EntraProviderConfig {
  const clientId = env.AUTH_MICROSOFT_ENTRA_ID_ID
  const tenantId = env.AUTH_MICROSOFT_ENTRA_ID_TENANT_ID
  if (!clientId || !tenantId) {
    throw new Error(
      'buildEntraProviderConfig: AUTH_MICROSOFT_ENTRA_ID_ID and AUTH_MICROSOFT_ENTRA_ID_TENANT_ID must both be set.',
    )
  }
  const issuer = `https://login.microsoftonline.com/${tenantId}/v2.0`
  const secret = env.AUTH_MICROSOFT_ENTRA_ID_SECRET
  if (secret) {
    return { clientId, clientSecret: secret, issuer }
  }
  return { clientId, issuer, client: { token_endpoint_auth_method: 'none' } }
}
