/*
 * Gate 3 Step 6 + 7: Accounts dispatch execution.
 *
 * Validates the accountsEntries (actualDispatched in [0, qtyRequested]
 * per row), computes the resulting dispatchStatus per Step 7 logic,
 * decrements inventory by the per-SKU actualDispatched sum, writes
 * Outward entries on each affected InventoryItem, and enqueues all
 * mutations atomically (one queue entry per record).
 *
 * Step 7 status logic:
 *   - every actualDispatched === 0       -> dispatchStatus stays 'Not Started'
 *   - any actualDispatched < qtyRequested AND any > 0 -> 'Pending' (partial)
 *   - every actualDispatched === qtyRequested        -> 'In Transit'
 *                                                       (joint spec section 11
 *                                                       updated logic; POD
 *                                                       upload flips to
 *                                                       'Delivered' at Step 8)
 *
 * Inventory side effect: per joint spec section 9, "Outward auto-
 * reduced after dispatch". One Outward entry per SKU per save with
 * { qty, dispatchId, schoolName, autoGenerated: true }; currentStock
 * decrements by the same amount. Outward entries are appended (not
 * replaced) so re-saves keep the historical trail.
 */

import type {
  AccountsDispatchEntry,
  AuditEntry,
  DispatchSummary,
  InventoryItem,
  KitDispatch,
  KitDispatchStatus,
} from '@/lib/types'
import { enqueueUpdate } from '@/lib/pendingUpdates'
import { kitDispatchRepo } from '@/lib/db/repos/kitDispatch'
import { currentBackend } from '@/lib/db/backend'
import { resolveInventoryItem } from '@/lib/inventory/resolveSku'

export interface AccountsExecuteArgs {
  mouId: string
  user: { id: string; name: string }
  accountsEntries: AccountsDispatchEntry[]
  expectedVersion?: number
}

export interface AccountsExecuteDeps {
  kitDispatches: KitDispatch[]
  inventory: InventoryItem[]
  enqueue?: typeof enqueueUpdate
  now?: () => Date
  /** P2b.X OCC #4: stub for tests. */
  updateAllocationsOCC?: typeof kitDispatchRepo.updateAllocationsOCC
}

export type AccountsFailureReason =
  | 'dispatch-not-found'
  | 'not-approved'
  | 'no-summary'
  | 'invalid-rows'
  | 'qty-over-requested'
  | 'version-conflict'

export type AccountsExecuteResult =
  | {
      ok: true
      dispatch: KitDispatch
      newDispatchStatus: KitDispatchStatus
      inventoryDecrements: Array<{ skuName: string; qty: number; newStock: number }>
    }
  | { ok: false; reason: AccountsFailureReason; offendingRow?: number; conflictVersion?: number }

function computeStatus(
  entries: AccountsDispatchEntry[],
  previous: KitDispatchStatus,
): KitDispatchStatus {
  if (entries.length === 0) return previous
  const allZero = entries.every((e) => e.qtyActualDispatched === 0)
  if (allZero) return previous === 'Not Started' ? 'Not Started' : previous
  const everyFull = entries.every((e) => e.qtyActualDispatched === e.qtyRequested)
  if (everyFull) {
    // Step 11 updated logic: full dispatch goes 'In Transit'; POD upload
    // later flips to 'Delivered'.
    return previous === 'Delivered' ? 'Delivered' : 'In Transit'
  }
  return 'Pending'
}

/**
 * Aggregate actual-dispatched quantity per resolved InventoryItem. Uses
 * the unified resolver so per-grade Cretile rows (sharing one skuName)
 * decrement their own grade's stock instead of collapsing onto whichever
 * Cretile row a name-only find() happened to return first.
 */
function aggregateByItem(
  entries: AccountsDispatchEntry[],
  inventory: InventoryItem[],
): Map<string, { item: InventoryItem; qty: number }> {
  const out = new Map<string, { item: InventoryItem; qty: number }>()
  for (const e of entries) {
    if (e.qtyActualDispatched <= 0) continue
    const item = resolveInventoryItem(inventory, {
      productName: e.productRequested,
      grade: e.grade,
    })
    // SKU vanished from inventory between allocation and execution (or a
    // Cretile grade with no stocked kit): skip the decrement and let ops
    // reconcile manually, same forgiving behaviour as before.
    if (!item) continue
    const existing = out.get(item.id)
    if (existing) existing.qty += e.qtyActualDispatched
    else out.set(item.id, { item, qty: e.qtyActualDispatched })
  }
  return out
}

export async function executeAccountsDispatch(
  args: AccountsExecuteArgs,
  deps: AccountsExecuteDeps,
): Promise<AccountsExecuteResult> {
  const enqueue = deps.enqueue ?? enqueueUpdate
  const now = (deps.now ?? (() => new Date()))()
  const isoNow = now.toISOString()

  const kd = deps.kitDispatches.find((k) => k.mouId === args.mouId)
  if (!kd) return { ok: false, reason: 'dispatch-not-found' }
  if (kd.salesApprovalStatus !== 'Approved') return { ok: false, reason: 'not-approved' }
  if (!kd.dispatchSummary) return { ok: false, reason: 'no-summary' }

  // Validate every row.
  for (let i = 0; i < args.accountsEntries.length; i += 1) {
    const r = args.accountsEntries[i]!
    if (!Number.isFinite(r.grade) || r.grade < 1 || r.grade > 12) {
      return { ok: false, reason: 'invalid-rows', offendingRow: i }
    }
    if (
      !Number.isFinite(r.qtyActualDispatched)
      || r.qtyActualDispatched < 0
    ) {
      return { ok: false, reason: 'invalid-rows', offendingRow: i }
    }
    if (r.qtyActualDispatched > r.qtyRequested) {
      return { ok: false, reason: 'qty-over-requested', offendingRow: i }
    }
  }

  const summary: DispatchSummary = {
    ...kd.dispatchSummary,
    accountsEntries: args.accountsEntries,
  }

  const newStatus = computeStatus(args.accountsEntries, kd.dispatchStatus)

  const dispatchAudit: AuditEntry = {
    timestamp: isoNow,
    user: args.user.id,
    action: 'status_change',
    before: {
      dispatchStatus: kd.dispatchStatus,
      accountsEntries: kd.dispatchSummary.accountsEntries,
    },
    after: { dispatchStatus: newStatus, accountsEntries: args.accountsEntries },
    notes: 'Accounts executed dispatch.',
  }

  const nextRecord: KitDispatch = {
    ...kd,
    dispatchStatus: newStatus,
    dispatchSummary: summary,
    auditLog: [...kd.auditLog, dispatchAudit],
  }

  if (deps.updateAllocationsOCC || currentBackend() === 'postgres') {
    const occ = deps.updateAllocationsOCC ?? kitDispatchRepo.updateAllocationsOCC.bind(kitDispatchRepo)
    const expectedVersion = args.expectedVersion ?? kd.version ?? 1
    const r = await occ(kd.id, expectedVersion, {
      dispatchStatus: newStatus,
      dispatchSummary: summary,
    }, dispatchAudit, { queuedBy: args.user.id })
    if (!r.ok) return { ok: false, reason: 'version-conflict', conflictVersion: r.conflictVersion }
    nextRecord.version = r.newVersion
  } else {
    await enqueue({
      queuedBy: args.user.id,
      entity: 'kitDispatch',
      operation: 'update',
      payload: {
        id: kd.id,
        mouId: args.mouId,
        record: nextRecord as unknown as Record<string, unknown>,
      },
    })
  }

  // Inventory decrement: one queue entry per affected InventoryItem,
  // resolved by (category, cretileGrade) for Cretile so each grade-band
  // kit decrements its own stock row.
  const totalsByItem = aggregateByItem(args.accountsEntries, deps.inventory)
  const inventoryDecrements: Array<{ skuName: string; qty: number; newStock: number }> = []
  for (const { item, qty } of Array.from(totalsByItem.values())) {
    const newStock = Math.max(0, item.currentStock - qty)
    const invAudit: AuditEntry = {
      timestamp: isoNow,
      user: args.user.id,
      action: 'inventory-decremented-by-dispatch',
      before: { currentStock: item.currentStock },
      after: { currentStock: newStock },
      notes: `Auto-outward ${qty} for ${kd.id} (${kd.schoolName})`,
    }
    inventoryDecrements.push({ skuName: item.skuName, qty, newStock })
    await enqueue({
      queuedBy: args.user.id,
      entity: 'inventoryItem',
      operation: 'update',
      payload: {
        id: item.id,
        skuName: item.skuName,
        outward: {
          qty,
          dispatchId: kd.id,
          schoolName: kd.schoolName,
          autoGenerated: true,
          timestamp: isoNow,
        },
        newStock,
        audit: invAudit as unknown as Record<string, unknown>,
      },
    })
  }

  return {
    ok: true,
    dispatch: nextRecord,
    newDispatchStatus: newStatus,
    inventoryDecrements,
  }
}
